import type { Metadata } from "next";
import "./globals.css";
import Providers from "./ui/providers";
import { Rubik } from "next/font/google";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
  weight: "variable",
});

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${rubik.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
