import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import Providers from "./ui/providers";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
